version: '3.4'

services:
  dockerdemo:
    container_name: dockerdemo
    ports:
    - 8040:443
    image: localhost:5000/dockerdemo
    build:
      context: .
      dockerfile: DockerDemo/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=test
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro

  eventstoredemo:
    container_name: evenstoredemo
    ports:
      - 8041:443
    image: localhost:5000/eventstoredemo
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=test
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro


  checkinservice:
    ports:
      - 8042:443
    container_name: checkinservice
    image: localhost:5000/checkinservice
    build:
      context: .
      dockerfile: CheckInService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=test
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro


  rabbitmq.messages:
    container_name: rabbitmqmessages
    ports:
      - 8043:443
    image: ${DOCKER_REGISTRY-}rabbitmqmessages
    build:
      context: .
      dockerfile: RabbitMQ.Messages/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=test
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
    - 5672:5672
    - 15672:15672 
