services:
  eventstoredb:
    container_name: CannonEvents
    image: eventstore/eventstore:latest
    environment:
      - EVENTSTORE_INSECURE=true 
      - EVENTSTORE_INT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113 
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-logs
        target: /var/log/eventstore

  checkinservice:
    ports:
      - 8042:443
    container_name: checkinservice
    image: localhost:5000/checkinservice
    build:
      context: .
      dockerfile: CheckInService/Dockerfile
    depends_on:
      - mssql
      - eventstoredb
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=test
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro

  rabbitmq.messages:
    container_name: rabbitmqmessages
    ports:
      - 8043:443
    image: localhost:5000/rabbitmqmessages
    build:
      context: .
      dockerfile: RabbitMQ.Messages/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=test
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    hostname: "rabbit"
    ports:
    - 5672:5672
    - 15672:15672 

  mssql:
    container_name: sql
    hostname: sql
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Rick@Sanchez"
    ports:
      - 1433:1433
    volumes:
      - sql:/var/opt/mssql

  patientservice:
    ports:
      - 8046:443
    container_name: patientservice
    image: localhost:5000/patientservice
    build:
      context: .
      dockerfile: PatientService/Dockerfile
    depends_on:
      - mssql
      - rabbitmq
      - eventstoredb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=test
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro

  importpatientservice:
    container_name: importpatientservice
    image: localhostL5000/importpatientservice
    build:
      context: .
      dockerfile: ImportPatientService/Dockerfile
    depends_on:
      - rabbitmq
volumes:
  sql:
  eventstore-data:
  eventstore-logs:  

